library("plyr")

source("game_mechanics.r")
source("interface.r")
source("sbot.r")
source("bot.r")

conf=rep(0,82)
strat=1:81
turn=1
rcd=NULL


learn_matrix=matrix(c(list(conf=rep(0,82)),rep(list(0),81)),1,82)

d=expand.grid(1:9,1:9)
hstrat=mdply(d,'paste',sep=",")[,3]

colnames(learn_matrix)=c("conf",hstrat)

learn_matrix=read.lm()  #file="learn_matrix.dat" generated by write.lm()
stat.lm()
###############
###############


learn_matrix=train(n=100, players=c("s","s"))

learn_matrix=train(n=100,players=c("m","s"))

learn_matrix=train(n=100,players=c("s","m"))

learn_matrix=train(n=100,players=c("m","m"))

stat.lm()


##  after match with human learn with higher weight:
##  learn_matrix=learn(wt=2)
##  TODO: allow varying weight  

write.lm()


